# enable color
alias ls='ls --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

# local bins
export PATH=$PATH:${HOME}/.local/bin
export PATH=$PATH:${HOME}/.cargo/bin
# Golang
export GOPATH=${HOME}/go
export PATH=$PATH:${GOPATH}/bin
