#!/bin/sh

set -u

is_command() {
	command -v "$1" >/dev/null
}

go_install() {
	package="$1"
	version="${2:-latest}"

	target="$package@$version"
	go install "$target" || >&2 echo "failed to install $target"
}

install_golangci() {
	if ! is_command curl
	then
		>&2 echo "curl not installed"
		return 1
	fi

	if is_command golangci-lint && [ "$(golangci-lint --version | cut -d ' ' -f 4)" = "1.46.2" ]
	then
		return 0
	fi

	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v1.46.2
	return $?
}

install_go_tools() {
	if ! is_command go
	then
		>&2 echo "go not installed"
		return 1
	fi

	go_install golang.org/x/tools/gopls
	go_install github.com/jesseduffield/lazygit
	go_install github.com/mattn/efm-langserver
	go_install github.com/nametake/golangci-lint-langserver
	install_golangci
}

install_rust_tools() {
	if ! is_command rustup
	then
		>&2 echo "rustup not installed"
		return 1
	fi

	rustup component add rls rust-analysis rust-src
}

install_npm_tools() {
	if ! is_command npm
	then
		>&2 echo "npm not installed"
		return 1
	fi

	npm i -g @ansible/ansible-language-server
	npm i -g bash-language-server
	npm i -g dockerfile-language-server-nodejs
	npm i -g dot-language-server
	npm i -g @emacs-grammarly/unofficial-grammarly-language-server
	npm i -g vscode-langservers-extracted
}

main() {
	install_go_tools
	install_rust_tools
	install_npm_tools
}

main
